### ISSUE TITLE
Add shadow to text in Banner

### ISSUE THREAD

**Issue by kunaljainwin** [kunaljainwin/Starflix#4]
[Banner.js](https://github.com/kunaljainwin/Starflix/blob/master/src/components/Banner.js)  Easy frontend issue . will get solved too soon

**Comment by ArinCodes** [comment]
I also want to work on this

**Comment by kunaljainwin** [comment]
@ArinCodes  you can but @Ommanimesh2  has done it so you can if you can make it better.
